export const players = [
  {
    id: "SFC001",
    name: "Lionel Messi",
    dob: new Date("1987-06-24"),
    height: 1.69,
    weight: 78.0,
    goals: 643,
    position: "Atacante",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC002",
    name: "Cristiano Ronaldo",
    dob: new Date("1985-02-05"),
    height: 1.87,
    weight: 85.0,
    goals: 719,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC003",
    name: "Neymar Jr",
    dob: new Date("1992-02-05"),
    height: 1.72,
    weight: 70.0,
    goals: 283,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC004",
    name: "Kylian Mbappé",
    dob: new Date("1998-12-20"),
    height: 1.82,
    weight: 75.0,
    goals: 171,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC005",
    name: "Robert Lewandowski",
    dob: new Date("1988-08-21"),
    height: 1.85,
    weight: 82.0,
    goals: 478,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC006",
    name: "Harry Kane",
    dob: new Date("1993-07-28"),
    height: 1.88,
    weight: 89.0,
    goals: 221,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC007",
    name: "Karim Benzema",
    dob: new Date("1987-12-19"),
    height: 1.87,
    weight: 83.0,
    goals: 392,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC008",
    name: "Sergio Agüero",
    dob: new Date("1988-06-02"),
    height: 1.72,
    weight: 70.0,
    goals: 368,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC009",
    name: "Zlatan Ibrahimović",
    dob: new Date("1981-10-03"),
    height: 1.95,
    weight: 95.0,
    goals: 570,
    position: "LEsquerdo",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC010",
    name: "Paulo Dybala",
    dob: new Date("1993-11-15"),
    height: 1.77,
    weight: 75.0,
    goals: 191,
    position: "LDireito",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC011",
    name: "Mauro Icardi",
    dob: new Date("1993-02-19"),
    height: 1.80,
    weight: 79.0,
    goals: 221,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC012",
    name: "Romelu Lukaku",
    dob: new Date("1993-05-13"),
    height: 1.90,
    weight: 92.0,
    goals: 222,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC013",
    name: "Gonzalo Higuaín",
    dob: new Date("1987-12-10"),
    height: 1.83,
    weight: 82.0,
    goals: 292,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC014",
    name: "Ciro Immobile",
    dob: new Date("1990-02-20"),
    height: 1.80,
    weight: 79.0,
    goals: 181,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC015",
    name: "Gabriel Jesus",
    dob: new Date("1997-04-03"),
    height: 1.75,
    weight: 72.0,
    goals: 121,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC016",
    name: "Roberto Firmino",
    dob: new Date("1991-10-02"),
    height: 1.81,
    weight: 76.0,
    goals: 141,
    position: "MCampo",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC017",
    name: "Edin Džeko",
    dob: new Date("1986-03-17"),
    height: 1.93,
    weight: 86.0,
    goals: 341,
    position: "LEsquerdo",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC018",
    name: "Olivier Giroud",
    dob: new Date("1986-09-30"),
    height: 1.92,
    weight: 88.0,
    goals: 231,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC019",
    name: "Mario Mandžukić",
    dob: new Date("1986-05-21"),
    height: 1.86,
    weight: 84.0,
    goals: 201,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC020",
    name: "Alvaro Morata",
    dob: new Date("1992-10-23"),
    height: 1.90,
    weight: 85.0,
    goals: 141,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC021",
    name: "Radamel Falcao",
    dob: new Date("1986-02-10"),
    height: 1.77,
    weight: 72.0,
    goals: 241,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC022",
    name: "Dries Mertens",
    dob: new Date("1987-05-06"),
    height: 1.69,
    weight: 65.0,
    goals: 181,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC023",
    name: "André Silva",
    dob: new Date("1995-11-06"),
    height: 1.85,
    weight: 84.0,
    goals: 81,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC024",
    name: "Wissam Ben Yedder",
    dob: new Date("1990-08-12"),
    height: 1.70,
    weight: 68.0,
    goals: 111,
    position: "Atacante",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC025",
    name: "Kevin De Bruyne",
    dob: new Date("1991-06-28"),
    height: 1.81,
    weight: 76.0,
    goals: 81,
    position: "Meio-campo",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC026",
    name: "N'Golo Kanté",
    dob: new Date("1991-03-29"),
    height: 1.69,
    weight: 68.0,
    goals: 21,
    position: "Volante",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC027",
    name: "Paul Pogba",
    dob: new Date("1993-03-15"),
    height: 1.91,
    weight: 84.0,
    goals: 81,
    position: "Meio-campo",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC028",
    name: "Luka Modrić",
    dob: new Date("1985-09-09"),
    height: 1.73,
    weight: 65.0,
    goals: 71,
    position: "Meio-campo",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC029",
    name: "Toni Kroos",
    dob: new Date("1990-01-04"),
    height: 1.83,
    weight: 76.0,
    goals: 41,
    position: "Meio-campo",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC030",
    name: "Mohamed Salah",
    dob: new Date("1992-06-15"),
    height: 1.75,
    weight: 71.0,
    goals: 181,
    position: "Ponta-direita",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC031",
    name: "Sadio Mané",
    dob: new Date("1992-04-10"),
    height: 1.75,
    weight: 69.0,
    goals: 141,
    position: "Ponta-esquerda",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC032",
    name: "Raheem Sterling",
    dob: new Date("1994-12-08"),
    height: 1.72,
    weight: 69.0,
    goals: 101,
    position: "LDireito",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC033",
    name: "Willian",
    dob: new Date("1988-08-09"),
    height: 1.75,
    weight: 76.0,
    goals: 121,
    position: "MCampo",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC034",
    name: "Alexis Sánchez",
    dob: new Date("1988-12-19"),
    height: 1.69,
    weight: 65.0,
    goals: 141,
    position: "LEsquerdo",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC035",
    name: "Mesut Özil",
    dob: new Date("1988-10-15"),
    height: 1.79,
    weight: 76.0,
    goals: 51,
    position: "MCampo",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC036",
    name: "Angel Di María",
    dob: new Date("1988-02-14"),
    height: 1.80,
    weight: 75.0,
    goals: 121,
    position: "MCampo",
    dominance: "Esquerdo",
    foot: "Direito"
  },
  {
    id: "SFC037",
    name: "Serge Gnabry",
    dob: new Date("1995-07-14"),
    height: 1.75,
    weight: 72.0,
    goals: 81,
    position: "LDireito",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC038",
    name: "Kingsley Coman",
    dob: new Date("1996-06-05"),
    height: 1.79,
    weight: 75.0,
    goals: 61,
    position: "LDireito",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC039",
    name: "Callum Wilson",
    dob: new Date("1992-02-27"),
    height: 1.80,
    weight: 76.0,
    goals: 91,
    position: "Atacante",
    dominance: "Direito",
    foot: "Esquerdo"
  },
  {
    id: "SFC040",
    name: "Ollie Watkins",
    dob: new Date("1995-12-30"),
    height: 1.80,
    weight: 75.0,
    goals: 41,
    position: "Zagueiro",
    dominance: "Direito",
    foot: "Esquerdo"
  }
  ];