export const players = [
    {
      id: "SFC001",
      name: "Lionel Messi",
      dob: "24 de Junho, 1987",
      height: "5'7\"",
      weight: "78 Kg",
      goals: 643,
      position: "Atacante",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC002",
      name: "Cristiano Ronaldo",
      dob: "5 de Fevereiro, 1985",
      height: "1,87",
      weight: "85 Kg",
      goals: 719,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC003",
      name: "Neymar Jr",
      dob: "5 de Fevereiro, 1992",
      height: "1,72",
      weight: "70 Kg",
      goals: 283,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC004",
      name: "Kylian Mbappé",
      dob: "20 de Dezembro, 1998",
      height: "1,82",
      weight: "75 Kg",
      goals: 171,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC005",
      name: "Robert Lewandowski",
      dob: "21 de Agosto, 1988",
      height: "1,85",
      weight: "82 Kg",
      goals: 478,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC006",
      name: "Harry Kane",
      dob: "28 de Julho, 1993",
      height: "1,88",
      weight: "89 Kg",
      goals: 221,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC007",
      name: "Karim Benzema",
      dob: "19 de Dezembro, 1987",
      height: "1,87",
      weight: "83 Kg",
      goals: 392,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC008",
      name: "Sergio Agüero",
      dob: "2 de Junho, 1988",
      height: "1,72",
      weight: "70 Kg",
      goals: 368,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC009",
      name: "Zlatan Ibrahimović",
      dob: "3 de Outubro, 1981",
      height: "1,95",
      weight: "95 Kg",
      goals: 570,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC010",
      name: "Paulo Dybala",
      dob: "15 de Novembro, 1993",
      height: "1,77",
      weight: "75 Kg",
      goals: 191,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC011",
      name: "Mauro Icardi",
      dob: "19 de Fevereiro, 1993",
      height: "1,80",
      weight: "79 Kg",
      goals: 221,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC012",
      name: "Romelu Lukaku",
      dob: "13 de Maio, 1993",
      height: "1,90",
      weight: "92 Kg",
      goals: 222,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC013",
      name: "Gonzalo Higuaín",
      dob: "10 de Dezembro, 1987",
      height: "1,83",
      weight: "82 Kg",
      goals: 292,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC014",
      name: "Ciro Immobile",
      dob: "20 de Fevereiro, 1990",
      height: "1,80",
      weight: "79 Kg",
      goals: 181,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC015",
      name: "Gabriel Jesus",
      dob: "3 de Abril, 1997",
      height: "1,75",
      weight: "72 Kg",
      goals: 121,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC016",
      name: "Roberto Firmino",
      dob: "2 de Outubro, 1991",
      height: "1,81",
      weight: "76 Kg",
      goals: 141,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC017",
      name: "Edin Džeko",
      dob: "17 de Março, 1986",
      height: "1,93",
      weight: "86 Kg",
      goals: 341,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC018",
      name: "Olivier Giroud",
      dob: "30 de Setembro, 1986",
      height: "1,92",
      weight: "88 Kg",
      goals: 231,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC019",
      name: "Mario Mandžukić",
      dob: "21 de Maio, 1986",
      height: "1,86",
      weight: "84 Kg",
      goals: 201,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC020",
      name: "Alvaro Morata",
      dob: "23 de Outubro, 1992",
      height: "1,90",
      weight: "85 Kg",
      goals: 141,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC021",
      name: "Radamel Falcao",
      dob: "10 de Fevereiro, 1986",
      height: "1,77",
      weight: "72 Kg",
      goals: 241,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC022",
      name: "Dries Mertens",
      dob: "6 de Maio, 1987",
      height: "1,69",
      weight: "65 Kg",
      goals: 181,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC023",
      name: "André Silva",
      dob: "6 de Novembro, 1995",
      height: "1,85",
      weight: "84 Kg",
      goals: 81,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC024",
      name: "Wissam Ben Yedder",
      dob: "12 de Agosto, 1990",
      height: "1,70",
      weight: "68 Kg",
      goals: 111,
      position: "Atacante",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC025",
      name: "Kevin De Bruyne",
      dob: "28 de Junho, 1991",
      height: "1,81",
      weight: "76 Kg",
      goals: 81,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC026",
      name: "N'Golo Kanté",
      dob: "29 de Março, 1991",
      height: "1,69",
      weight: "68 Kg",
      goals: 21,
      position: "Volante",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC027",
      name: "Paul Pogba",
      dob: "15 de Março, 1993",
      height: "1,91",
      weight: "84 Kg",
      goals: 81,
      position: "Meio-campo",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC028",
      name: "Luka Modrić",
      dob: "9 de Setembro, 1985",
      height: "1,73",
      weight: "65 Kg",
      goals: 71,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC029",
      name: "Toni Kroos",
      dob: "4 de Janeiro, 1990",
      height: "1,83",
      weight: "76 Kg",
      goals: 41,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC030",
      name: "Mohamed Salah",
      dob: "15 de Junho, 1992",
      height: "1,75",
      weight: "71 Kg",
      goals: 181,
      position: "Ponta-direita",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC031",
      name: "Sadio Mané",
      dob: "10 de Abril, 1992",
      height: "1,75",
      weight: "69 Kg",
      goals: 141,
      position: "Ponta-esquerda",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC032",
      name: "Raheem Sterling",
      dob: "8 de Dezembro, 1994",
      height: "1,72",
      weight: "69 Kg",
      goals: 101,
      position: "Ponta-direita",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC033",
      name: "Willian",
      dob: "9 de Agosto, 1988",
      height: "1,75",
      weight: "76 Kg",
      goals: 121,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC034",
      name: "Alexis Sánchez",
      dob: "19 de Dezembro, 1988",
      height: "1,69",
      weight: "65 Kg",
      goals: 141,
      position: "Ponta-esquerda",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC035",
      name: "Mesut Özil",
      dob: "15 de Outubro, 1988",
      height: "1,79",
      weight: "76 Kg",
      goals: 51,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC036",
      name: "Angel Di María",
      dob: "14 de Fevereiro, 1988",
      height: "1,80",
      weight: "75 Kg",
      goals: 121,
      position: "Meio-campo",
      dominance: "Esquerdo",
      foot: "Direito"
    },
    {
      id: "SFC037",
      name: "Serge Gnabry",
      dob: "14 de Julho, 1995",
      height: "1,75",
      weight: "72 Kg",
      goals: 81,
      position: "Ponta-direita",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC038",
      name: "Kingsley Coman",
      dob: "5 de Junho, 1996",
      height: "1,79",
      weight: "75 Kg",
      goals: 61,
      position: "Ponta-esquerda",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC039",
      name: "Callum Wilson",
      dob: "27 de Fevereiro, 1992",
      height: "1,80",
      weight: "76 Kg",
      goals: 91,
      position: "Atacante",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC040",
      name: "Ollie Watkins",
      dob: "30 de Dezembro, 1995",
      height: "1,80",
      weight: "75 Kg",
      goals: 41,
      position: "Atacante",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC041",
      name: "Dominic Calvert-Lewin",
      dob: "16 de Março, 1997",
      height: "1,87",
      weight: "82 Kg",
      goals: 51,
      position: "Atacante",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC042",
      name: "Tammy Abraham",
      dob: "2 de Outubro, 1997",
      height: "1,90",
      weight: "85 Kg",
      goals: 41,
      position: "Atacante",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC043",
      name: "Michail Antonio",
      dob: "28 de Março, 1990",
      height: "1,80",
      weight: "75 Kg",
      goals: 41,
      position: "Ponta-direita",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC044",
      name: "Richarlison",
      dob: "10 de Maio, 1997",
      height: "1,84",
      weight: "76 Kg",
      goals: 51,
      position: "Ponta-esquerda",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC045",
      name: "James Maddison",
      dob: "23 de Novembro, 1996",
      height: "1,75",
      weight: "72 Kg",
      goals: 21,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC046",
      name: "Youri Tielemans",
      dob: "7 de Maio, 1997",
      height: "1,76",
      weight: "72 Kg",
      goals: 21,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC047",
      name: "Wilfried Ndidi",
      dob: "16 de Dezembro, 1996",
      height: "1,83",
      weight: "76 Kg",
      goals: 11,
      position: "Volante",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC048",
      name: "Rúben Neves",
      dob: "13 de Março, 1997",
      height: "1,80",
      weight: "75 Kg",
      goals: 21,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC049",
      name: "Bruno Fernandes",
      dob: "8 de Setembro, 1994",
      height: "1,79",
      weight: "72 Kg",
      goals: 41,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    },
    {
      id: "SFC050",
      name: "Bernardo Silva",
      dob: "10 de Agosto, 1994",
      height: "1,73",
      weight: "65 Kg",
      goals: 21,
      position: "Meio-campo",
      dominance: "Direito",
      foot: "Esquerdo"
    }
  ];